package no.ntnu.supportprim.data.util;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import javax.validation.constraints.NotNull;

/**
 * Generate a patient's unique identifier.
 * @author: Amar Jaiswal
 */
public class PatientIdGenerator {
    private static final Log LOG = LogFactory.getLog(PatientIdGenerator.class.getName());

    /**
     * Patient ID generator. Currently it is based on Infopad's attribute values as listed below.
     * The ID is generated by concatenating the ordered attribute list,
     * [clinicId, projectId, journalId, and birthYear], separated by "-" respectively.
     *
     * @param clinicId
     * @param projectId
     * @param journalId
     * @param birthYear
     * @return
     */
    public static String generateId(String clinicId, String projectId, String journalId, String birthYear) {

        String patientId = clinicId + "-" + projectId + "-" + journalId + "-" + birthYear;
        LOG.debug("Patient id : " + patientId);

        return patientId;
    }

    public static String generatePid(@NotNull String clinicId, @NotNull String journalId, @NotNull String birthYear) {

        String patientId = clinicId + "_" + journalId + "_" + birthYear;
        LOG.debug("Patient id : " + patientId);

        return patientId;
    }
}
